### ISSUE TITLE
Signed commits

### ISSUE THREAD

**Issue by mpyszynski** [coopnorge/engineering-github-actions#21]
Currently bot commits unsigned commits. Some repositories require to have all commits signed, because of this policy bot's PRs are blocked and cannot be merged

**Comment by nhhagen** [comment]
The GitHub Action we use to create the pull requests support signing the commits, lets configure that.

https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#commit-signing

**Comment by AtzeDeVries** [comment]
last time i checked creating PR's with a github action bot did not trigger actions when creating a PR. That is why we are using a PAT. This could be updated now.

**Comment by pravindahal** [comment]
Signed commits are enabled now: https://github.com/coopnorge/engineering-github-actions/pull/92

**Comment by nhhagen** [comment]
Resolved by
- https://github.com/coopnorge/engineering-github-actions/pull/92
