### ISSUE TITLE
Make update-infrastructure-repo.yaml close old PRs updating the infrastructure

### ISSUE THREAD

**Issue by nhhagen** [coopnorge/engineering-github-actions#40]
Currently the workflow only opens new PRs leaving un-merged old PRs around. If you merge an older PR the newer ones will have a merge conflict.

I suggest that the default options is to close old infra update PRs when creating a new one.

**Comment by bendiknesbo** [comment]
With the new labels on the deployment-PRs, we now have at least two different possible solutions for this issue:
1. When creating a new deployment-PR, close any other open deployment-PR's for that same environment&service.
2. When creating a new deployment-PR, add `Closes #<number>` for all of the other open deployment-PR for that same environment&service.

**Comment by nhhagen** [comment]
I suggest we mimic what Dependabot and renovate does, close all other PRs (for env and service) with a link to the PR that replaces the open ones.
